#if !canImport(ObjectiveC)
import XCTest

extension HRT2DSceneTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HRT2DSceneTests = [
        ("testInit", testInit),
    ]
}

extension SKNode_GeometryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SKNode_GeometryTests = [
        ("testCenterPosition", testCenterPosition),
        ("testCornerPosition", testCornerPosition),
        ("testNoRepositioning", testNoRepositioning),
    ]
}

extension SKView_GeometryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SKView_GeometryTests = [
        ("testAspectFillSceneScale", testAspectFillSceneScale),
        ("testAspectFitSceneScale", testAspectFitSceneScale),
        ("testFillSceneScale", testFillSceneScale),
        ("testResizeSceneScale", testResizeSceneScale),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HRT2DSceneTests.__allTests__HRT2DSceneTests),
        testCase(SKNode_GeometryTests.__allTests__SKNode_GeometryTests),
        testCase(SKView_GeometryTests.__allTests__SKView_GeometryTests),
    ]
}
#endif
